version: "3.8"

services:
  wpdbwsl:
    image: mariadb:10.4
    volumes:
      - natm_data_wsl:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - db.env

  wpwebwsl:
    depends_on:
      - wpdbwsl
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
      - type: bind
        source: ./uploads.ini
        target: /usr/local/etc/php/conf.d/uploads.ini
      - type: bind
        source: ./.bashrc
        target: /root/.bashrc
      - type: bind
        source: ./.ssh
        target: /root/.ssh
    ports:
      - "8080:80"
    restart: always
    env_file:
      - wp.env

volumes:
  wp_data_wsl:
    name: website_wp_data_wsl
